'use client';
import { useState } from 'react';
import { Card, PageTitle } from '@/components/UI';
import { classifyGarbage } from '@/lib/cognitive';
import { detectPrivacyLevel } from '@/src/integrations/gateway/safetyGate';
import { routeModelTask } from '@/src/integrations/gateway/modelGateway';
import { garbageInputs as seed } from '@/lib/mock';
import type { GarbageInput } from '@/lib/types';
export default function GarbageStation() { const privacyPreview = detectPrivacyLevel(seed[0]?.content ?? ''); const gatewayDecision = routeModelTask({ taskId: 'garbage-classify-preview', userId: 'demo', modelIntent: 'cheap_batch', messages: [{ role: 'user', content: seed[0]?.content ?? '' }], privacyLevel: privacyPreview, requiresCaching: true }); const [items, setItems] = useState<GarbageInput[]>(seed); return <div><PageTitle eyebrow="Garbage Station" title="垃圾站">垃圾不是垃圾，是未分类的残差。失败案例、错题、工单、AI 跑偏输出与灵感碎片会被分类、脱敏和转卡。</PageTitle><Card><p className="mb-4 text-sm text-plankton">Integration Gateway：隐私预检 {privacyPreview}，分类路由到 {gatewayDecision.providerId}；高隐私只走 local/mock local。</p><form className="grid gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); setItems([{ id: `g${Date.now()}`, content: String(f.get('content')), source: 'idea_fragment', domain: 'demo', creator: 'demo' }, ...items]); e.currentTarget.reset(); }}><textarea name="content" required placeholder="粘贴失败案例 / 灵感碎片，试试手机号、身份证、车牌、学校姓名" className="min-h-28 rounded-xl bg-white/10 p-3"/><button className="w-fit rounded-xl bg-coral/20 px-5 py-3 text-coral">分类并脱敏</button></form></Card><section className="mt-6 grid gap-4 md:grid-cols-2">{items.map(g => { const c = classifyGarbage(g); return <Card key={g.id}><p className="text-tide">{g.source} · {g.domain}</p><h3 className="mt-2 text-xl font-semibold">{c.classification}</h3><p className="mt-3 text-white/65">隐私风险：{c.privacyRisk}</p><p className="mt-3 rounded-2xl bg-black/20 p-4 text-sm text-white/75">{c.redactedContent}</p></Card>; })}</section></div>; }
