import { describe, expect, it } from 'vitest';
import { calculateVersionFitness, compareVersions, createCounterpointRelation, createVersionNode, detectVersionConflicts, promoteToCanonical, reviewVersion, shouldRequireHumanReview, getVersionFamily } from '../../src/polyphony';
import { setupBasicPolyphony } from './helpers';
describe('polyphony policy and comparison', () => {
  it('compareVersions returns a diff summary', () => { const { base, experimental } = setupBasicPolyphony(); const other = createVersionNode({ familyId: base.familyId, voiceTrackId: experimental.id, parentVersionIds: [base.id], title: 'Other', summary: 'different', contentRef: 'ref://other', authorIds: ['u2'], status: 'experimental', riskLevel: 'medium', privacyLevel: 'team', safetyScore: 82, metadata: {} }); const diff = compareVersions(base.id, other.id); expect(diff.summary).toContain('Base'); expect(diff.changedFields).toContain('title'); });
  it('calculateVersionFitness combines safety, usefulness, compressionScore and cache profile', () => { const { base } = setupBasicPolyphony(); expect(calculateVersionFitness(base.id)).toBeGreaterThan(60); });
  it('public cache versions must be public privacy and pass safety threshold', () => { const { family, stable } = setupBasicPolyphony(); const node = createVersionNode({ familyId: family.id, voiceTrackId: stable.id, parentVersionIds: [], title: 'Public cache impact', summary: 'shared', contentRef: 'ref://public', authorIds: ['u1'], status: 'active', riskLevel: 'low', privacyLevel: 'team', safetyScore: 90, safetyMetadata: { requiresHumanReview: false, affectsPublicCache: true, affectsExternalActions: false, affectsHumanTransition: false, containsSensitiveData: false }, metadata: {} }); expect(promoteToCanonical(node.id).allowed).toBe(false); });
  it('rejected version cannot enter canonical', () => { const { family, stable } = setupBasicPolyphony(); const rejected = createVersionNode({ familyId: family.id, voiceTrackId: stable.id, parentVersionIds: [], title: 'Rejected', summary: 'bad', contentRef: 'ref://rejected', authorIds: ['u1'], status: 'rejected', riskLevel: 'low', privacyLevel: 'team', safetyScore: 90, metadata: {} }); expect(promoteToCanonical(rejected.id).allowed).toBe(false); });
  it('promoteToCanonical updates VersionFamily.canonicalVersionId', () => { const { family, base } = setupBasicPolyphony(); reviewVersion(base.id, { reviewerId: 'human', clarity: 90, usefulness: 90, safety: 92, reusability: 88, originality: 80, compatibility: 90, recommendation: 'promote_to_canonical', comment: 'ok' }); expect(promoteToCanonical(base.id).allowed).toBe(true); expect(getVersionFamily(family.id)?.canonicalVersionId).toBe(base.id); });
  it('detectVersionConflicts recognizes conflicts, extends and supports relations', () => { const { base, experimental, safety } = setupBasicPolyphony(); const child = createVersionNode({ familyId: base.familyId, voiceTrackId: experimental.id, parentVersionIds: [base.id], title: 'Child', summary: 'extends', contentRef: 'ref://child', authorIds: ['u2'], status: 'experimental', riskLevel: 'low', privacyLevel: 'team', safetyScore: 85, metadata: {} }); const support = createVersionNode({ familyId: base.familyId, voiceTrackId: safety.id, parentVersionIds: [], title: 'Support', summary: 'supports', contentRef: 'ref://support', authorIds: ['u3'], status: 'active', riskLevel: 'low', privacyLevel: 'team', safetyScore: 90, metadata: {} }); const risky = createVersionNode({ familyId: base.familyId, voiceTrackId: safety.id, parentVersionIds: [], title: 'Risky', summary: 'conflicts', contentRef: 'ref://risky', authorIds: ['u3'], status: 'active', riskLevel: 'critical', privacyLevel: 'private', safetyScore: 40, metadata: {} }); createCounterpointRelation(risky.id, base.id, 'conflicts', 'critical risk blocks stable release'); const findings = detectVersionConflicts([base.id, child.id, support.id, risky.id]); expect(findings.some((item) => item.relationType === 'extends')).toBe(true); expect(findings.some((item) => item.relationType === 'supports')).toBe(true); expect(findings.some((item) => item.relationType === 'conflicts')).toBe(true); });
  it('shouldRequireHumanReview returns true for high risk', () => { const { base } = setupBasicPolyphony(); expect(shouldRequireHumanReview({ ...base, riskLevel: 'high' })).toBe(true); });
});
