import { describe, expect, it } from 'vitest';
import { createVersionNode, createVoiceTrack, freezeVersion, getActivePolyphony, promoteToCanonical, updateVersionNode } from '../../src/polyphony';
import { setupBasicPolyphony } from './helpers';
describe('polyphony version node policies', () => {
  it('high risk version cannot promote canonical', () => { const { family, stable } = setupBasicPolyphony(); const high = createVersionNode({ familyId: family.id, voiceTrackId: stable.id, parentVersionIds: [], title: 'High', summary: 'risk', contentRef: 'ref://high', authorIds: ['u1'], status: 'active', riskLevel: 'high', privacyLevel: 'team', safetyScore: 95, metadata: {} }); expect(promoteToCanonical(high.id).allowed).toBe(false); });
  it('critical risk version cannot promote canonical', () => { const { family, stable } = setupBasicPolyphony(); const critical = createVersionNode({ familyId: family.id, voiceTrackId: stable.id, parentVersionIds: [], title: 'Critical', summary: 'risk', contentRef: 'ref://critical', authorIds: ['u1'], status: 'active', riskLevel: 'critical', privacyLevel: 'team', safetyScore: 95, metadata: {} }); expect(promoteToCanonical(critical.id).allowed).toBe(false); });
  it('quarantined version does not enter active polyphony', () => { const { family, stable } = setupBasicPolyphony(); createVersionNode({ familyId: family.id, voiceTrackId: stable.id, parentVersionIds: [], title: 'Quarantine', summary: 'risk', contentRef: 'ref://q', authorIds: ['u1'], status: 'quarantined', riskLevel: 'high', privacyLevel: 'private', safetyScore: 20, metadata: {} }); expect(getActivePolyphony(family.id).versionNodes.every((node) => node.status !== 'quarantined')).toBe(true); });
  it('world_model voice track must contain uncertainty metadata', () => { const { family } = setupBasicPolyphony(); const world = createVoiceTrack(family.id, 'world_model', 'World', 'uncertainty'); expect(() => createVersionNode({ familyId: family.id, voiceTrackId: world.id, parentVersionIds: [], title: 'World', summary: 'prediction', contentRef: 'ref://world', authorIds: ['u1'], status: 'active', riskLevel: 'medium', privacyLevel: 'community', safetyScore: 85, metadata: {} })).toThrow('uncertainty metadata'); });
  it('frozen version cannot continue to be modified', () => { const { base } = setupBasicPolyphony(); freezeVersion(base.id, 'archive'); expect(() => updateVersionNode({ ...base, title: 'changed' })).toThrow('frozen'); });
});
