export type WorldType = 'single_player_game' | 'online_game_replay' | 'online_game_official_api' | 'simulation' | 'anime_world' | 'original_virtual_world' | 'real_world_scenario';
export type WorldConnectorStatus = 'mock' | 'connected' | 'disabled' | 'error' | 'requires_authorization';
export type WorldActionPermission = 'read_only' | 'replay_analysis' | 'training_mode' | 'sandbox_write' | 'official_api_write' | 'no_write';
export type ExperienceFeedbackType = 'bug' | 'balance' | 'emotion' | 'immersion' | 'difficulty' | 'learning' | 'strategy' | 'safety' | 'world_model_error' | 'residual_discovery';
export type WorldPrivacyLevel = 'public' | 'community' | 'team' | 'private';
export type WorldRiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type WorldDomain = 'education' | 'insurance' | 'industry' | 'gameplay' | 'anime' | 'creative' | 'world_model' | 'training' | 'safety';

export interface LicensePolicy { licenseType: 'original' | 'authorized' | 'fan_noncommercial' | 'unknown' | 'restricted'; owner?: string; allowedUses: string[]; forbiddenUses: string[]; allowDerivativeScenes: boolean; allowTrainingUse: boolean; attributionRequired: boolean; }
export interface WorldSafetyPolicy { allowCheatAutomation: false; allowLiveMultiplayerControl: false; allowRealMoneyAutomation: false; allowExternalHarmOptimization: false; requiresHumanReviewForActions: boolean; minorDataPolicy: 'high_privacy' | 'not_allowed' | 'guardian_consent_required'; }
export interface WorldConnector { id: string; name: string; worldType: WorldType; status: WorldConnectorStatus; source: 'official_api' | 'authorized_sdk' | 'mod_api' | 'replay_file' | 'user_upload' | 'mock'; permissions: WorldActionPermission[]; capabilities: { readState: boolean; importReplay: boolean; exportScene: boolean; receiveEvents: boolean; sendSuggestions: boolean; sandboxActions: boolean; multiplayerLiveControl: false; }; licensePolicy: LicensePolicy; safetyPolicy: WorldSafetyPolicy; }
export interface WorldCapsule { id: string; title: string; worldType: WorldType; domain: WorldDomain; description: string; sourceConnectorId?: string; licensePolicy: LicensePolicy; privacyLevel: WorldPrivacyLevel; riskLevel: WorldRiskLevel; sceneStateSchema?: Record<string, unknown>; allowedActions: string[]; forbiddenActions: string[]; linkedResidualCardIds: string[]; linkedSkillIds: string[]; linkedWorldModelSpecIds: string[]; createdBy: string; createdAt: string; version: string; status: 'draft' | 'active' | 'reviewing' | 'public_candidate' | 'public' | 'quarantined' | 'deprecated'; experienceCount?: number; }
export interface ExperienceEvent { id: string; sessionId: string; timestamp: string; eventType: 'state_observed' | 'choice_made' | 'failure' | 'success' | 'confusion' | 'emotion_marker' | 'strategy_note' | 'safety_flag' | 'residual_found'; summary: string; rawRef?: string; metadata: Record<string, unknown>; }
export interface ExperienceSession { id: string; userId: string; worldCapsuleId: string; connectorId?: string; startedAt: string; endedAt?: string; durationSeconds?: number; mode: 'observe' | 'play' | 'replay_review' | 'sandbox_test' | 'story_experience'; consentId: string; events: ExperienceEvent[]; feedbackIds: string[]; privacyLevel: WorldPrivacyLevel; dataSensitivity?: 'low' | 'medium' | 'high'; containsMinorData?: boolean; proofStatus: 'unverified' | 'self_reported' | 'replay_verified' | 'system_verified' | 'rejected'; }
export interface ExperienceFeedback { id: string; sessionId: string; userId: string; feedbackType: ExperienceFeedbackType; title: string; content: string; usefulnessScore?: number; clarityScore?: number; evidenceStrength?: number; emotionalIntensity?: number; residualValue?: number; safetyConcern?: boolean; linkedResidualCardId?: string; suggestedSkillId?: string; suggestedWorldModelUpdate?: string; status: 'draft' | 'submitted' | 'reviewing' | 'accepted' | 'rejected' | 'assetized'; createdAt: string; }
export interface ProofOfExperience { id: string; sessionId: string; userId: string; worldCapsuleId: string; proofType: 'manual_attestation' | 'replay_hash' | 'event_log_hash' | 'trusted_connector' | 'human_review'; proofHash: string; timestamp: string; verificationStatus: 'pending' | 'verified' | 'failed'; privacyLevel: WorldPrivacyLevel; }
export interface ExperienceRewardEvent { id: string; userId: string; sessionId: string; feedbackId?: string; rewardType: 'feed_points' | 'glow_shards' | 'tester_reputation' | 'experience_credit' | 'compression_credit' | 'cosmetic_unlock'; amount: number; reason: string; status: 'pending' | 'released' | 'blocked'; createdAt: string; }
export interface TesterReputation { userId: string; domains: Record<string, number>; feedbackAccuracy: number; acceptedFeedbackCount: number; rejectedFeedbackCount: number; biasFlags: number; trustLevel: 'new' | 'trusted' | 'expert' | 'moderated'; }
export interface WorldAction { connectorId?: string; actionType: string; summary: string; liveMultiplayer?: boolean; realMoney?: boolean; realWorldImpact?: boolean; targetDomain?: string; }
export interface WorldExperienceSummary { sessionId: string; title: string; durationSeconds: number; keyEvents: string[]; feedbackCount: number; proofStatus: ExperienceSession['proofStatus']; residualOpportunities: string[]; requiresHumanReview: boolean; }
export interface WorldModelExperienceUpdate { id: string; feedbackId: string; updateSummary: string; assumptions: string[]; confidence: number; requiresHumanReview: boolean; createdAt: string; }
