export type VersionStatus = 'draft' | 'active' | 'experimental' | 'reviewing' | 'merge_candidate' | 'canonical' | 'deprecated' | 'frozen' | 'rejected' | 'quarantined';
export type VoiceTrackType = 'stable' | 'experimental' | 'safety' | 'aesthetic' | 'low_cost' | 'domain_specific' | 'community' | 'codex_auto' | 'human_review' | 'world_model' | 'gameplay' | 'ecosystem' | 'open_source' | 'human_transition';
export type CounterpointRelationType = 'supports' | 'conflicts' | 'extends' | 'specializes' | 'forks' | 'remixes' | 'supersedes' | 'requires_review' | 'contradicts' | 'converges_with' | 'blocks_public_release';
export type VersionedObjectType = 'whitepaper' | 'residual_card' | 'wish_card' | 'reverse_wish_card' | 'skill_capsule' | 'shared_cache_object' | 'prompt_template' | 'review_rubric' | 'human_transition_policy' | 'ui_theme' | 'avatar_morph_template' | 'cosmetic_preset' | 'agent_policy' | 'world_model_spec' | 'integration_connector' | 'ecosystem_policy' | 'game_season' | 'cognitive_map_region' | 'cognitive_prosthesis';
export type PolyphonyRiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type VersionPrivacyLevel = 'public' | 'community' | 'team' | 'private';

export interface VersionFamily { id: string; objectType: VersionedObjectType; objectId: string; title: string; description?: string; createdBy: string; createdAt: string; updatedAt: string; canonicalVersionId?: string; voiceTrackIds: string[]; versionNodeIds: string[]; tags: string[]; visibility: VersionPrivacyLevel; }
export interface VoiceTrack { id: string; familyId: string; name: string; type: VoiceTrackType; purpose: string; ownerId?: string; contributorIds: string[]; status: 'active' | 'paused' | 'archived'; createdAt: string; updatedAt: string; }
export interface CostProfile { estimatedTokenCost?: number; estimatedComputeCost?: number; cacheHitRate?: number; expectedReuseCount?: number; }
export interface UncertaintyMetadata { assumptions: string[]; confidence: number; knownUnknowns: string[]; failureConditions: string[]; lastValidatedAt?: string; }
export interface SafetyMetadata { requiresHumanReview: boolean; affectsPublicCache: boolean; affectsExternalActions: boolean; affectsHumanTransition: boolean; containsSensitiveData: boolean; }
export interface VersionNode { id: string; familyId: string; voiceTrackId: string; parentVersionIds: string[]; childVersionIds: string[]; title: string; summary: string; contentRef: string; contentHash: string; authorIds: string[]; createdAt: string; updatedAt: string; status: VersionStatus; riskLevel: PolyphonyRiskLevel; privacyLevel: VersionPrivacyLevel; validationScore?: number; compressionScore?: number; safetyScore?: number; usefulnessScore?: number; originalityScore?: number; reusabilityScore?: number; costProfile?: CostProfile; uncertaintyMetadata?: UncertaintyMetadata; safetyMetadata?: SafetyMetadata; metadata: Record<string, unknown>; }
export interface CounterpointRelation { id: string; familyId: string; fromVersionId: string; toVersionId: string; relationType: CounterpointRelationType; explanation: string; createdBy: string; createdAt: string; }
export interface MergeProposal { id: string; familyId: string; sourceVersionIds: string[]; targetVoiceTrackId?: string; proposedTitle: string; proposedSummary: string; conflictSummary: string; resolutionPlan: string; riskAssessment: string; proposedBy: string; reviewerIds: string[]; status: 'draft' | 'reviewing' | 'approved' | 'rejected' | 'merged'; createdAt: string; updatedAt: string; }
export interface VersionReview { id: string; versionId: string; reviewerId: string; clarity: number; usefulness: number; safety: number; reusability: number; originality: number; compatibility: number; recommendation: 'keep_parallel' | 'promote_to_canonical' | 'merge' | 'revise' | 'deprecate' | 'quarantine'; comment: string; createdAt: string; }
export interface VersionDiff { versionAId: string; versionBId: string; summary: string; changedFields: string[]; conflicts: string[]; riskDifference: string; useCaseDifference: string; suggestedAction: 'keep_parallel' | 'merge' | 'prefer_a' | 'prefer_b' | 'needs_review'; }
export interface CodexTaskResult { taskId: string; title: string; prompt: string; summary: string; changedFiles?: string[]; diffRef?: string; testResult?: 'pass' | 'fail' | 'not_run'; outputArtifactRef?: string; voiceTrackType: VoiceTrackType; riskNotes?: string; createdAt: string; }
export interface CodexPolyphonyTask { taskId: string; title: string; prompt: string; voiceTrackType: VoiceTrackType; constraints: string[]; doneWhen: string[]; testCommand: string; safetyNotes: string[]; }
export interface ActivePolyphony { family: VersionFamily; voiceTracks: VoiceTrack[]; versionNodes: VersionNode[]; canonicalVersion?: VersionNode; mergeProposals: MergeProposal[]; quarantinedCount: number; }
export interface VersionLineage { version: VersionNode; parents: VersionNode[]; children: VersionNode[]; ancestors: VersionNode[]; descendants: VersionNode[]; relations: CounterpointRelation[]; }
export interface PolyphonySummary { familyId: string; title: string; canonicalTitle?: string; activeVoiceCount: number; activeVersionCount: number; reviewingCount: number; mergeCandidateCount: number; quarantinedCount: number; highRiskCount: number; recommendedAction: string; }
