import type { CacheRewardEvent, SharedCacheObject } from './types';
import { resetCacheRegistry } from './sharedCache/cacheObjectRegistry';
import { recordCacheHit } from './sharedCache/cacheHitLedger';
import { calculateCacheReward } from './economy/cacheRewardEngine';

const consentAll = { allowPrivate: true, allowTeamShare: true, allowCommunityShare: true, allowPublicShare: true, allowTrainingUse: false, allowDerivativeSkills: true, allowAttribution: true, allowAnonymousAttribution: false };
const provenance = { originalContributorId: 'u-lan', ideaNotaryHash: 'hash-edu-001', timestamp: '2026-05-08T00:00:00Z', parentObjectIds: [], transformationSteps: ['redacted', 'reviewed', 'verified compression'], reviewIds: ['r1'], verificationIds: ['v1'] };

export const sharedCacheObjects: SharedCacheObject[] = [
  { id: 'cache-skill-edu-baby', type: 'skill_capsule', title: '压轴题婴儿版讲解', domain: 'education', sourceLayer: 'community', targetLayer: 'public', privacyLevel: 'low', riskLevel: 'low', ownerId: 'u-lan', organizationId: 'team-edu', contributors: ['u-lan', 'u-moon'], provenance, consent: consentAll, licenseMode: 'public_commons', status: 'public_skill', version: '1.2.0', createdAt: '2026-05-01T00:00:00Z', updatedAt: '2026-05-08T00:00:00Z', usageCount: 46, cacheHitCount: 28, reviewScore: 91, verifiedCompressionScore: 68, qualityScore: 88, safetyScore: 94, anonymized: true, promotionHistory: [{ from: 'team', to: 'community', at: '2026-05-03T00:00:00Z', by: 'review-pool', result: 'approved' }, { from: 'community', to: 'public', at: '2026-05-06T00:00:00Z', by: 'public-review', result: 'approved' }] },
  { id: 'cache-skill-objection', type: 'skill_capsule', title: '客户异议识别', domain: 'customer-success', sourceLayer: 'team', targetLayer: 'team', privacyLevel: 'medium', riskLevel: 'medium', ownerId: 'u-moon', organizationId: 'team-edu', contributors: ['u-moon'], provenance: { ...provenance, ideaNotaryHash: 'hash-cs-002' }, consent: { ...consentAll, allowPublicShare: false }, licenseMode: 'team_internal', status: 'team_verified', version: '0.8.0', createdAt: '2026-05-02T00:00:00Z', updatedAt: '2026-05-08T00:00:00Z', usageCount: 9, cacheHitCount: 4, reviewScore: 78, verifiedCompressionScore: 33, qualityScore: 75, safetyScore: 82, anonymized: true, promotionHistory: [] },
  { id: 'cache-residual-industrial', type: 'residual_card', title: '工业工单总结残差', domain: 'industrial', sourceLayer: 'private', targetLayer: 'team', privacyLevel: 'low', riskLevel: 'low', ownerId: 'u-lan', organizationId: 'team-edu', contributors: ['u-lan'], provenance: { ...provenance, ideaNotaryHash: 'hash-ind-003' }, consent: consentAll, licenseMode: 'community_share', status: 'team_candidate', version: '0.2.0', createdAt: '2026-05-04T00:00:00Z', updatedAt: '2026-05-08T00:00:00Z', usageCount: 2, cacheHitCount: 1, reviewScore: 74, verifiedCompressionScore: 22, qualityScore: 79, safetyScore: 91, anonymized: true, promotionHistory: [] },
  { id: 'cache-private-sensitive', type: 'failure_case', title: '含手机号客户失败案例', domain: 'insurance', sourceLayer: 'private', targetLayer: 'private', privacyLevel: 'high', riskLevel: 'high', ownerId: 'u-lan', contributors: ['u-lan'], provenance: { ...provenance, ideaNotaryHash: 'hash-private-004' }, consent: { ...consentAll, allowTeamShare: false, allowCommunityShare: false, allowPublicShare: false }, licenseMode: 'private', status: 'private', version: '0.1.0', createdAt: '2026-05-05T00:00:00Z', updatedAt: '2026-05-08T00:00:00Z', usageCount: 0, cacheHitCount: 0, reviewScore: 40, verifiedCompressionScore: 0, qualityScore: 40, safetyScore: 20, anonymized: false, promotionHistory: [] }
];

resetCacheRegistry(sharedCacheObjects);
export const sampleCacheHit = recordCacheHit('cache-skill-edu-baby', 'u-moon', 'task-edu-1');
export const sampleRewards: CacheRewardEvent[] = calculateCacheReward(sampleCacheHit);
