import { describe, expect, it } from 'vitest';
import type { ExperienceFeedback, TesterReputation, WorldConnector } from '../../src/worlds/types';
import { calculateExperienceReward, connectWorldCapsuleToSkill, createAnimeWorldCapsule, createExperienceSession, createWorldCapsule, defaultTesterReputation, detectCheatRisk, detectIPRisk, evaluateWorldAction, generateProofOfExperience, generateTesterReputationUpdate, getWorldCapsule, importReplayAsExperienceSession, recordExperienceEvent, resetExperienceFeedback, resetExperienceSessions, resetProofsOfExperience, resetWorldCapsules, resetWorldConnectors, routeFeedbackToResidualCard, scoreFeedbackQuality, stableProofHash, submitExperienceFeedback, updateWorldModelFromExperience, validateWorldConnector } from '../../src/worlds';
import { makeMockWorldConnector, originalLicense, safeWorldPolicy } from '../../src/worlds/connectors/mockConnectorFactory';
import { registerWorldConnector } from '../../src/worlds/gateway/worldConnectorRegistry';

function resetWorlds() { resetExperienceFeedback(); resetExperienceSessions(); resetProofsOfExperience(); resetWorldCapsules(); resetWorldConnectors(); }
function capsule() { return createWorldCapsule({ id: 'cap-1', title: '村庄经济循环模拟', worldType: 'single_player_game', domain: 'gameplay', description: '测试资源、任务、奖励循环是否自洽', licensePolicy: originalLicense, privacyLevel: 'team', riskLevel: 'low', allowedActions: ['sandbox'], forbiddenActions: ['cheat'], createdBy: 'tester', version: '0.1.0', status: 'active' }); }
function feedback(overrides: Partial<ExperienceFeedback> = {}): ExperienceFeedback { return { id: 'fb-1', sessionId: 's1', userId: 'u1', feedbackType: 'residual_discovery', title: 'clear feedback', content: '资源奖励缺少可见因果解释，第三轮后玩家困惑。', usefulnessScore: 90, clarityScore: 90, evidenceStrength: 88, residualValue: 92, status: 'accepted', createdAt: '2026-05-08T00:00:00Z', ...overrides }; }

describe('World Experience Gateway safety and rewards', () => {
  it('unauthorized IP world capsule cannot enter public', () => { resetWorlds(); expect(() => createWorldCapsule({ ...capsule(), id: 'bad-ip', licensePolicy: { ...originalLicense, licenseType: 'unknown' }, privacyLevel: 'public', status: 'public' })).toThrow('cannot enter public'); });
  it('online game live control must be rejected', () => { resetWorlds(); const connector = makeMockWorldConnector('online', 'online', 'online_game_replay', { permissions: ['read_only', 'replay_analysis', 'no_write'] }); const decision = evaluateWorldAction(connector, { actionType: 'live control', summary: '真人网游自动操控', liveMultiplayer: true }); expect(decision.allowed).toBe(false); });
  it('replay analysis is allowed', () => { resetWorlds(); const connector = makeMockWorldConnector('replay', 'replay', 'online_game_replay', { permissions: ['read_only', 'replay_analysis', 'no_write'] }); const decision = evaluateWorldAction(connector, { actionType: 'replay_analysis', summary: 'analyze uploaded replay only' }); expect(decision.allowed).toBe(true); });
  it('connector allowLiveMultiplayerControl and capability must stay false', () => { const connector: WorldConnector = makeMockWorldConnector('safe', 'safe', 'simulation'); expect(connector.safetyPolicy.allowLiveMultiplayerControl).toBe(false); expect(connector.capabilities.multiplayerLiveControl).toBe(false); expect(validateWorldConnector(connector).allowed).toBe(true); });
  it('minor session data is marked high privacy', () => { resetWorlds(); const cap = capsule(); const connector = registerWorldConnector(makeMockWorldConnector('single', 'single', 'single_player_game')); const session = createExperienceSession('minor', cap.id, 'play', { connectorId: connector.id, containsMinorData: true }); expect(session.privacyLevel).toBe('private'); expect(session.dataSensitivity).toBe('high'); });
  it('low quality repeated feedback cannot receive reward', () => { const fb = feedback({ title: 'spam', content: '重复' }); const proof = { id: 'p1', sessionId: 's1', userId: 'u1', worldCapsuleId: 'cap', proofType: 'manual_attestation' as const, proofHash: 'h', timestamp: 't', verificationStatus: 'verified' as const, privacyLevel: 'team' as const }; const rewards = calculateExperienceReward(fb, proof, defaultTesterReputation('u1')); expect(rewards.every((reward) => reward.status === 'blocked')).toBe(true); });
  it('high quality feedback with proof can receive experienceCredit', () => { const proof = { id: 'p1', sessionId: 's1', userId: 'u1', worldCapsuleId: 'cap', proofType: 'event_log_hash' as const, proofHash: 'h', timestamp: 't', verificationStatus: 'verified' as const, privacyLevel: 'team' as const }; const rewards = calculateExperienceReward(feedback(), proof, defaultTesterReputation('u1')); expect(rewards.some((reward) => reward.rewardType === 'experience_credit' && reward.amount > 0 && reward.status === 'released')).toBe(true); });
  it('ExperienceFeedback can generate ResidualCard', () => { const residual = routeFeedbackToResidualCard(feedback()); expect(residual.residualId).toContain('res-feedback'); expect(residual.reusable).toBe(true); });
  it('ExperienceFeedback links residual back to its session WorldCapsule', () => { resetWorlds(); const cap = capsule(); const session = createExperienceSession('u1', cap.id, 'sandbox_test'); const fb = submitExperienceFeedback(session.id, { feedbackType: 'residual_discovery', title: '因果缺口', content: '玩家无法理解奖励为什么出现，需要中间状态反馈', evidenceStrength: 82, residualValue: 88 }); const residual = routeFeedbackToResidualCard(fb); const updated = connectWorldCapsuleToSkill(cap.id, 'skill-loop-explain'); expect(updated?.linkedSkillIds).toContain('skill-loop-explain'); expect(getWorldCapsule(cap.id)?.linkedResidualCardIds).toContain(residual.residualId); expect(residual.domain).toBe('gameplay'); });
  it('WorldCapsule can connect SkillCapsule', () => { resetWorlds(); const cap = capsule(); const updated = connectWorldCapsuleToSkill(cap.id, 'skill-npc-dialogue'); expect(updated?.linkedSkillIds).toContain('skill-npc-dialogue'); });
  it('high risk real world bridge update requires human review', () => { const update = updateWorldModelFromExperience(feedback({ suggestedWorldModelUpdate: '工业安全报警建议', safetyConcern: true })); expect(update.requiresHumanReview).toBe(true); });
  it('Anime world capsule must check licensePolicy', () => { resetWorlds(); expect(() => createAnimeWorldCapsule({ ...capsule(), id: 'anime', worldType: 'anime_world', licensePolicy: { ...originalLicense, licenseType: 'unknown' } })).toThrow('licensePolicy'); });
  it('Cheat risk action is blocked by safety gate', () => { const connector = makeMockWorldConnector('c', 'c', 'online_game_replay', { permissions: ['read_only', 'replay_analysis'] }); expect(detectCheatRisk(connector, { actionType: 'aimbot', summary: 'bypass anti-cheat' }).blocked).toBe(true); });
  it('tester reputation updates accepted and rejected feedback', () => { const user: TesterReputation = defaultTesterReputation('u1'); const accepted = generateTesterReputationUpdate(user, { feedback: feedback(), accepted: true, domain: 'gameplay' }); const rejected = generateTesterReputationUpdate(accepted, { feedback: feedback({ id: 'fb-2' }), accepted: false, domain: 'gameplay' }); expect(rejected.acceptedFeedbackCount).toBe(1); expect(rejected.rejectedFeedbackCount).toBe(1); });
  it('ProofOfExperience hash is stable', () => { expect(stableProofHash('same')).toBe(stableProofHash('same')); });
  it('feedback reward does not directly depend on durationSeconds', () => { const proof = { id: 'p1', sessionId: 's1', userId: 'u1', worldCapsuleId: 'cap', proofType: 'event_log_hash' as const, proofHash: 'h', timestamp: 't', verificationStatus: 'verified' as const, privacyLevel: 'team' as const }; const a = calculateExperienceReward(feedback(), proof, defaultTesterReputation('u1'), 1)[0].amount; const b = calculateExperienceReward(feedback(), proof, defaultTesterReputation('u1'), 99999)[0].amount; expect(a).toBe(b); });
  it('importReplayAsExperienceSession records replay review event and proof', () => { resetWorlds(); const cap = capsule(); registerWorldConnector(makeMockWorldConnector('replay-c', 'replay', 'online_game_replay', { permissions: ['read_only', 'replay_analysis', 'no_write'] })); const session = importReplayAsExperienceSession('match.rep', { userId: 'u1', worldCapsuleId: cap.id, connectorId: 'replay-c' }); recordExperienceEvent(session.id, { eventType: 'strategy_note', summary: '只做回放分析', metadata: {} }); const proof = generateProofOfExperience(session); expect(proof.proofHash).toContain('poe-'); });
  it('IP risk detects restricted capsule public risk', () => { resetWorlds(); const cap = createWorldCapsule({ ...capsule(), id: 'restricted', licensePolicy: { ...originalLicense, licenseType: 'restricted' }, status: 'reviewing' }); expect(detectIPRisk(cap).allowedPublic).toBe(false); });
  it('submitExperienceFeedback attaches feedback to session', () => { resetWorlds(); const cap = capsule(); const session = createExperienceSession('u1', cap.id, 'sandbox_test'); const fb = submitExperienceFeedback(session.id, { feedbackType: 'bug', title: 'bug', content: '按钮没有反馈导致体验失败', evidenceStrength: 70, residualValue: 70 }); expect(fb.sessionId).toBe(session.id); expect(scoreFeedbackQuality(fb)).toBeGreaterThan(40); });
});
